### ISSUE TITLE
Menu component (routing)

### ISSUE THREAD

**Issue by jingyophuong** [Systems-Development-and-Frameworks/code_party_kp#14]
5. Create a menu component with a `<nuxt-link>` to `/login` if the user is
   not logged in. If the user is logged in, it shows a logout button. You might
   want to put this this menu component in your `layouts/default.vue`.
   Furthermore, you might want to use [Vuex](https://vuex.vuejs.org/) for a
   globally accessible `isAuthenticated` getter method. There is a [nuxt integration](https://nuxtjs.org/docs/2.x/directory-structure/store).

**Comment by KarakoA** [comment]
Blocked by #12

**Comment by KarakoA** [comment]
Globol accessor provided (`auth.isAuthenticated`), can be accessed as a computed property via [mapGetters shorthand](https://vuex.vuejs.org/guide/getters.html#the-mapgetters-helper) or by writing it out fully (`this.$state.auth...`)
