### ISSUE TITLE
Buttons based on state

### ISSUE THREAD

**Issue by jingyophuong** [Systems-Development-and-Frameworks/code_party_kp#15]
7. Your buttons should behave according to the authentication state. E.g. you
   could only display `upvote` when the user is logged in. Alternatively,
   you could redirect to `/login` if the user is not logged in.
   Add a `delete` and `edit` button to your news-entries which only shows for authors.
   Connecting them to your backend is optional though.

**Comment by KarakoA** [comment]
Blocked by #12
